### ISSUE TITLE
upgrade umbrella charts to migrate to rbac.authorization.k8s.io/ve

### ISSUE THREAD

**Issue by databus23** [sapcc/helm-charts#3362]
Once #3360 is merged we need to bump chart dependencies to facilitate the actual rollout:

- [ ] event-exporter `0.2.6` in `kube-monitoring-*`
- [ ] k8s-secrets-certificate-exporter `1.3.3` in `kube-monitoring-*`
- [ ] watch-cache-exporter `0.1.4` in `kube-monitoring-*`
- [ ] disco `1.6.3` in `kube-system-*`
- [ ] kube-fip-controller `0.1.13` in `kube-system-*`
- [ ] node-problem-detector `1.3.9` in `kube-system-*`
